pipeline:
  image_build:
    image: plugins/docker
    repo: vivit/maguro
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_PULL_REQUEST}
    when:
      event: pull_request

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: ping_github_ci
    when:
      status: [ success, failure ]
