channels:
  - CA88ED2AK # ping_github_ci
  - CA34H1551 # sandbox_dev
  - G0H5UB23W # deploy

repositories:
  - name: 'vivitInc/maguro'
    env:
      - production
  - name: 'vivitInc/magnolia'
    env:
      - ingress
      - heapster
      - drone
  - name: 'vivitInc/vivit-corporate'
    env:
      - production
  - name: 'vivitInc/clover'
    env:
      - build_production
      - build_ci
  - name: 'vivitInc/maguro'
    env:
      - production

schedules:
  - name: 'vivitInc/github-label-sync'
    cron: '0 0 0 * * *'
